Repository ita-social-projects/StreetCode, pull requests merged in 2023-08, with the labels that each got.

#549 Rate limiting middleware
  Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: enhancement

#558 Fix/Text displaying with related words
  Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
Labels: bug

#621 team fix
  Streetcode/Streetcode.BLL/DTO/Team/TeamMemberDTO.cs
  Streetcode/Streetcode.DAL/Entities/Team/TeamMember.cs
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Labels: bug

#624 fix related term
  Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
Labels: bug

#636 added handler for TickerString and fixed team create
  Streetcode/Streetcode.BLL/DTO/Team/TeamMemberDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Team/GetNamePosition/GetTickerStringHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Team/GetNamePosition/GetTickerStringQuery.cs
  Streetcode/Streetcode.WebApi/Controllers/Team/TickerStringController.cs
Labels: bug, enhancement

#679 Add pagination to street code arts/backend
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/GetPageByStreetcodeId/GetPageOfArtsByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/GetPageByStreetcodeId/GetPageOfArtsByStreetcodeIdQuery.cs
  Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
  Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/StreetcodeArtController.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedFigure/GetRelatedFiguresByStreetcodeIdHandlerTests.cs
Labels: bug
