Repository ita-social-projects/StreetCode, pull requests merged in 2023-07, with the labels that each got.

#328 fix publish and draft date
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
Labels: bug

#322 delete text
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/TextUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
Labels: bug

#355 Fix update
  Streetcode/Streetcode.BLL/Mapping/Streetcode/RelatedFigureProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetAllPublished/GetAllPublishedHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetAllPublished/GetAllPublishedQuery.cs
  Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/RelatedFigureController.cs
  Streetcode/Streetcode.WebApi/appsettings.Local.json
Labels: bug

#319 [416] Terms and Text fix on Streetcode Page.
  Streetcode/Streetcode.BLL/Interfaces/Text/ITextService.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedTerm/Delete/DeleteRelatedTermCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedTerm/Delete/DeleteRelatedTermHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetParsed/GetParsedTextAdminPreviewHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetParsed/GetParsedTextForAdminPreviewCommand.cs
  Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/RelatedTermController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Delete/DeleteRelatedTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Services/Text/AddTermsToTextServiceTests.cs
Labels: bug, enhancement

#287 Added tests for FindStreetcodesWithMatchTitle() FindSortedStreetcodes() FindFilteredStreetcodes() in GetAllStreetcodehandler
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
Labels: Test case

#271 Fixed CreateRelatedTermHandlerTest, GetTransactLinByStreetcodeIdHandl…
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Delete/DeleteRelatedTermHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllMainTeamHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Transactions/TransactionsTests/TransactionLinkTests/GetTransactLinkByStreetcodeIdHandlerTests.cs
Labels: Test case

#498 fix streetcode deleting
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Delete/DeleteStreetcodeHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/DeleteStreetcodeHandlerTests.cs
Labels: bug

#495 Fix catalog streetcodes displaying images
  Streetcode/Streetcode.BLL/DTO/Streetcode/Catalog/CatalogItem.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/Catalog/CatalogItemProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogQuery.cs
Labels: bug, duplicate

#516 478 admintext and video block an error is thrown when previewing the main text
  Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Text/TextPreviewDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/UpdateParsed/UpdateParsedTextAdminPreviewHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/UpdateParsed/UpdateParsedTextForAdminPreviewCommand.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
Labels: bug

#529 Fix tags order
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/GetByStreetcodeId/GetTagByStreetcodeIdHandler.cs
Labels: bug, duplicate

#534 fix text load
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
Labels: bug
