Repository ita-social-projects/StreetCode, pull requests merged in 2023-05, with the labels that each got.

#198 Created for fans admin back. Made new endpoints, Mapper and MediatR methods.
  Streetcode/Streetcode.BLL/Mapping/Media/Images/ImageProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Sources/SourceLinkCategoryProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/GetAllCategoriesHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/GetAllCategoriesQuery.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryHandler.cs
  Streetcode/Streetcode.DAL/Entities/Sources/SourceLinkCategory.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ImageController.cs
  Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
Labels: (Epic#3) Other pages

#210 fixing photo on related figures and catalog
  Streetcode/Streetcode.BLL/Mapping/Streetcode/CatalogProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/RelatedFigureProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogHandler.cs
Labels: bug

#225 [Features] Added new endpoints for existing streetcodes
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/WithUrlExist/StreetcodeWithUrlExistHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/WithUrlExist/StreetcodeWithUrlExistQuery.cs
  Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
Labels: bug, (Epic#2) Admin/New StreetCode

#229 Update development
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/AdditionalContent/SubtitleUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/TextUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/AdditionalContent/SubtitleProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/TextContent/TextProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: enhancement

#232 check for image delete
  Streetcode/Streetcode.BLL/MediatR/Newss/Update/UpdateNewsHandler.cs
Labels: bug

#236 Fixed conditions when updating news without image and creating news w…
  Streetcode/Streetcode.BLL/MediatR/Newss/Create/CreateNewsHandler.cs
Labels: enhancement

#237 Instagram api
  Streetcode/Streetcode.BLL/Interfaces/Instagram/IInstagramService.cs
  Streetcode/Streetcode.BLL/MediatR/Instagram/GetAll/GetAllPostsHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Instagram/GetAll/GetAllPostsQuery.cs
  Streetcode/Streetcode.BLL/Services/Instagram/InstagramEnvirovmentVariables.cs
  Streetcode/Streetcode.BLL/Services/Instagram/InstagramService.cs
  Streetcode/Streetcode.BLL/Services/Payment/PaymentEnvirovmentVariables.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.DAL/Entities/Instagram/InstagramPost.cs
  Streetcode/Streetcode.DAL/Entities/Instagram/InstagramPostResponse.cs
  Streetcode/Streetcode.WebApi/Controllers/Instagram/InstagramController.cs
  Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: enhancement

#240 Streetcode update smile
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/Interface/IChanged.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/Media/VideoUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/FactUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/HistoricalContextUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/RelatedFigureUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/StreetcodeArtUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/TimelineItemUpdateDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/Interfaces/IDeleted.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: enhancement
