Repository ita-social-projects/StreetCode, pull requests merged in 2023-06, with the labels that each got.

#254 Feature blob storage cleaning
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: enhancement

#261 added another arg to the blob service constructor
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Labels: bug, enhancement

#260 [Update] Streetcode update coordinates and category content
  Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Update/StreetcodeCoordinateUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Analytics/Update/StatisticRecordUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Sources/Update/StreetcodeCategoryContentUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/AdditionalContent/Coordinates/StreetcodeCoordinateProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Analytics/StatisticRecordProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Sources/StreetcodeCategoryContentProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
Labels: enhancement

#250 Created news API for newsPage optimization
  Streetcode/Streetcode.BLL/DTO/News/NewsDTOWithURLs.cs
  Streetcode/Streetcode.BLL/DTO/News/RandomNewsDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlQuery.cs
  Streetcode/Streetcode.WebApi/Controllers/Newss/NewsController.cs
Labels: (Epic#3) Other pages

#274 Added p tags around news text
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Labels: bug, enhancement, (Epic#3) Other pages

#264 Unit tests for team link and positions endpoints
  Streetcode/Streetcode.BLL/MediatR/Team/Position/Create/CreatePositionHandler.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/CreatePositionTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/GetAllPositionTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/TeamMemberLink/CreateTeamMembersLinkTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/TeamMemberLink/GetAllTeamMembersLinksTest.cs
Labels: issue

#267 Added unit tests for Team and News mediatrs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/GetNewsByIdTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/GetNewsByUrlTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/CreateTeamTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/UpdateTeamTest.cs
Labels: issue

#270 UnitTest Fix and create
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Audio/GetAllAudioHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/SortedByDateTimeHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/CreateTermHandlerTests.cs
Labels: issue

#280 Update README.md
  README.md
Labels: documentation

#273 #272 Tests for news
  Streetcode/Streetcode.XUnitTest/MediatRTests/News/CreateNewsTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/News/DeleteNewsTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/News/GetAllNewsTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/News/UpdateNewsTest.cs
Labels: duplicate, enhancement

#266 Unit tests for "Team" MediatR.
  Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/DeleteTeamTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/GetAllTeamsTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/GetByIdTeamTest.cs
Labels: duplicate, enhancement

#291 290 cors configuration
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: issue

#307 Integration tests for Blob Service
  .gitignore
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
  Streetcode/Streetcode.WebApi/Extensions/ConfigurationBuilderExtensions.cs
  Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
  Streetcode/Streetcode.WebApi/appsettings.IntegrationTests.json
  Streetcode/Streetcode.XIntegrationTest/Base/IntegrationTestBase.cs
  Streetcode/Streetcode.XIntegrationTest/Base/TestDBFixture.cs
  Streetcode/Streetcode.XIntegrationTest/Properties/launchSettings.json
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/CleanBlobTest/CleanBlobServiceTests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/DeleteFileTest/DeleteFileInStorageTest.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/FindFileTests/FindFileInStorageAsBase64Tests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/FindFileTests/FindFileInStorageAsMemoryStreamTests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/SaveFileTests/SaveFileInStorageBase64Tests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/SaveFileTests/SaveFileInStorageTests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/UpdateFileTest/UpdateFileInStorageTests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/Utils/BlobServiceTestBase.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/Utils/BlobStorageFixture.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/Utils/testData.json
  Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
Labels: issue

#313 removed image, only send image id
  Streetcode/Streetcode.BLL/DTO/Media/Art/ArtCreateUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Media/Images/ImageUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Media/Images/StreetcodeImageUpdateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
  Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Media/Images/ArtProfile.cs
  Streetcode/Streetcode.BLL/Mapping/Media/Images/ImageProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
Labels: bug
