Repository ita-social-projects/StreetCode, pull requests merged in 2024-01, with the labels that each got.

#863 Fix integrated tests valerii
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetById/GetSubtitleByIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/GetByStreetcodeId/GetTagByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Art/GetByStreetcodeId/GetArtsByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/Image/GetByStreetcodeId/GetImageByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/GetByStreetcodeId/GetStreetcodeArtByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
  Streetcode/Streetcode.BLL/Services/CacheService/CacheService.cs
  Streetcode/Streetcode.DAL/Streetcode.DAL.csproj
  Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
  Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
  Streetcode/Streetcode.WebApi/Extensions/RecurringJobExtensions.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/CoordinateControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/SubtitleControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/TagControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/BaseControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/AudioControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/Images/ArtControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/Images/StreetcodeArtControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/VideoControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Coordinate/ExtractTestStreetcodeCoordinate.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Coordinate/ExtractTestToponymCoordinate.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Subtitle/ExtractTestSubtitle.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Tag/ExtractTestTag.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Tag/StreetcodeTagIndexSetup.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/Art/ExtractTestArt.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/Image/ExtractTestImage.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/StreetcodeArt/ExtractTestStreetcodeArt.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Video/ExtractTestVideo.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Partners/ExtractTestPartners.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Source/SourceLinkCategories/ExtractTestSourceLinkCategory.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractTestStreetcode.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/RelatedFigure/ExtractTestRelatedFigure.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Facts/ExtractTestFact.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Terms/ExstractTestTerm.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Texts/ExstractTestText.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Timelines/ExtractTestTimelineItem.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Toponyms/ExtractTestToponym.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Transactions/ExtractTestTransactionLink.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/CustomWebApplicationFactory.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/SqlDbHelper.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/StreetcodeClient.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/CleanBlobTest/CleanBlobServiceTests.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/Utils/BlobStorageFixture.cs
  Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
Labels: Sev: major, Pri: low, Functional

#1002 Update 'Setup' section in README.md
  README.md
Labels: documentation

#975 Integration test cases Create Streetcode
  Streetcode/Streetcode.WebApi/appsettings.IntegrationTests.json
  Streetcode/Streetcode.WebApi/appsettings.Local.json
  Streetcode/Streetcode.WebApi/appsettings.json
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/CoordinateControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/TagControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/BaseControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/AudioControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/Images/StreetcodeArtControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/VideoControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Streetcode/Create/StreetcodeCreateControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Coordinate/ExtractTestStreetcodeCoordinate.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Coordinate/ExtractTestToponymCoordinate.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Subtitle/ExtractTestSubtitle.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Tag/ExtractTestTag.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/AdditionalContent/Tag/StreetcodeTagIndexSetup.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/Art/ExtractTestArt.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/Image/ExtractTestImage.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Images/StreetcodeArt/ExtractTestStreetcodeArt.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Media/Video/ExtractTestVideo.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Partners/ExtractTestPartners.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Source/SourceLinkCategories/ExtractTestSourceLinkCategory.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractCreateTestStreetCode.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractTestStreetcode.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/RelatedFigure/ExtractTestRelatedFigure.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/StreetcodeIndexFetch.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Facts/ExtractTestFact.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Terms/ExstractTestTerm.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/TextContent/Texts/ExstractTestText.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Timelines/ExtractTestTimelineItem.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Toponyms/ExtractTestToponym.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Transactions/ExtractTestTransactionLink.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/CustomWebApplicationFactory.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/StreetcodeClient.cs
  Streetcode/Streetcode.XIntegrationTest/ServiceTests/BlobServiceTests/Utils/BlobStorageFixture.cs
Labels: Test case, Sev: minor, Pri: medium

#323 Middleware Implementation
  DeleteTextTest.cs
  GetAllTextsTest.cs
  GetStreetcodeArtByStreetcodeIdTest.cs
  GetTextByIdTest.cs
  GetTextByStreetcodeIdTest.cs
  Logo-1.png
  StreerCodeLogo2.jpg
  StreetCodeLogo.jpg
  Streetcode/Streetcode.BLL/Interfaces/Logging/ILoggerService.cs
  Streetcode/Streetcode.BLL/Middleware/ApiRequestResponseMiddleware.cs
  Streetcode/Streetcode.BLL/Middleware/MiddlewareExtension.cs
  Streetcode/Streetcode.BLL/Middleware/RequestResponseMiddlewareOptions.cs
  Streetcode/Streetcode.BLL/Services/Logging/LoggerService.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.WebApi/appsettings.json
Labels: duplicate, enhancement, issue

#1048 Integration tests streetcode update
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/AdditionalContent/CoordinateControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Media/VideoControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Streetcode/Update/StreetcodeUpdateControllerTests.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractTestStreetcode.cs
  Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractTestUpdateStreetcode.cs
  Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
Labels: Test case
